checks:
  python:
    code_rating: true
    duplicate_code: true
  javascript: true

build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        before:
#          - 'sudo apt-get install chromium-browser'
          - 'python -mpip install pip setuptools coverage pyvirtualdisplay -U'
        override:
          -
            command: coverage run --omit=manga_py/cli/args/*.py,manga_py/providers/__list.py --source=manga_py setup.py test || true
            coverage:
              file: '.coverage'
              format: 'py-cc'
#          - py-scrutinizer-run
      environment:
        python: 3.6.6
        node: 6.0.0
filter:
  excluded_paths:
    - tests/*.py