#!/usr/bin/python3
# -*- coding: utf-8 -*-

import providers.bulumanga_com
import providers.bato_to
import providers.com_x_life
import providers.comico_jp
import providers.comicsandmanga_ru
import providers.desu_me
import providers.eatmanga_me
import providers.funmanga_com
import providers.gogomanga_co
import providers.goodmanga_net
import providers.heymanga_me
import providers.inmanga_com
import providers.jurnalu_ru
import providers.kissmanga_com
import providers.manga_online_biz
import providers.manga_online_com_ua
import providers.mangabb_co
import providers.mangabox_me
import providers.mangachan_me
import providers.mangaclub_ru
import providers.mangadoom_co
import providers.mangaeden_com
import providers.mangafox_me
import providers.mangafreak_net
import providers.mangago_me
import providers.mangahead_me
import providers.mangahere_co
import providers.mangahome_com
import providers.mangahub_ru
import providers.mangainn_net
import providers.mangakakalot_com
import providers.mangaleader_com
import providers.mangalife_us
import providers.mangalib_me
import providers.mangamove_com
import providers.manganel_com
import providers.mangaonlinehere_com
import providers.mangapanda_com
import providers.mangapark_me
import providers.mangareader_net
import providers.mangaroot_com
import providers.mangarussia_com
import providers.mangasaurus_com
import providers.mangasupa_com
import providers.mangatan_net
import providers.mangatown_com
import providers.manhuagui_com
import providers.mintmanga_com
import providers.myreadingmanga_info
import providers.ninemanga_com
import providers.read_yagami_me
import providers.readmanga_me
import providers.readmanga_eu
import providers.readms_net
import providers.selfmanga_ru
import providers.shakai_ru
import providers.somanga_net
import providers.tapas_io
import providers.tenmanga_com
import providers.unixmanga_nl
import providers.wmanga_ru
import providers.viz_com
import providers.yaoichan_me
import providers.zingbox_me
import providers.zip_read_com
import providers.otakusmash_com
